-- On commence par charger les différentes librairies utilisées par le jeu,
-- afin d'y avoir accès dans toutes les scènes et les modules du jeu

Object      = require "libs.classic"
local Core  = require "core"
local Game  = require "game"
utils       = require "libs.loveutils"

-- On charge après cela les différentes scènes, qui sont les différents types
-- d'écrant avec lesquels le joueur interagira
scenes      = require "scenes"

love.graphics.setDefaultFilter( "nearest", "nearest", 1 )
io.stdout:setvbuf("no")

function love.load() -- On charge la scene de départ (pour l'instant le menu, bientôt une scene spéciale pour ça)
  core = Core()
  game = Game()
  game.pigmanager:addPig("cochon")

  scenes.MainMenu()
end

function love.update(dt)
  core:update(dt)
end

function love.draw()
  core:draw()
end

function love.mousemoved(x, y, dx, dy)
  core:mousemoved(x, y, dx, dy)
end

function love.mousepressed( x, y, button, istouch )
  core:mousepressed(x, y, button, istouch)
end
